Skip FirefoxAccounts during Firefox CSV Import
bitwarden/jslib pull request #323
Opened 2021-04-05 20:38 UTC by tzdybal

Firefox exports 'chrome://FirefoxAccounts' if Firefox Accouts are usedin browser. It's quite hacky - password field in CSV is actually a JSON encoded data, not a password.
Because it's not a useful record, it should be skipped during import.

This PR adds filtering and unit test for Firefox importer.

2021-04-05 20:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/jslib?pullRequest=323) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/jslib?pullRequest=323) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/jslib?pullRequest=323) it.</sub>

2021-04-05 21:26 UTC, cscharf reviewed
Thanks for the submission! Outside of some formatting issues I _think_ this looks okay. Would like @MGibson1 to take a quick peek at the unit tests as well. Overall please ensure member/property indentation and level-alignment (using spaces only) matches across the board.

2021-04-05 21:26 UTC, cscharf commented on src/importers/firefoxCsvImporter.ts
> +			return value.url !== "chrome://FirefoxAccounts"
formatting (this line and L17 below it), alignment and spacing of indentation should match rest of document.

2021-04-05 21:26 UTC, cscharf commented on spec/common/importers/firefoxCsvImporter.spec.ts
> +			login: Object.assign(new LoginView(), {
spacing / indentation misalignment.

2021-04-05 23:01 UTC, MGibson1 approved these changes
Looks good, thanks! I don't see how the linter didn't pick this up, but thanks!

2021-04-05 23:07 UTC, MGibson1 requested changes

2021-04-05 23:07 UTC, MGibson1 commented on spec/common/importers/firefoxCsvImporter.spec.ts
> +const CipherData = [
I know this matches the lastpass importer tests, but to clean up these test files, I'd prefer the csv strings exported from a testData file similar to SafeInCloud and 1Password export data.

2021-04-05 23:07 UTC, MGibson1 commented
Sorry about reversing that approval! for some reason when I first clicked review it showed me only spacing fixes. 🤷

2021-04-11 18:55 UTC, tzdybal commented
Test data is now in separate files, and this time I fixed all linter errors before commiting ;)

2021-04-11 22:09 UTC, MGibson1 approved these changes
Looks good, thanks!

2021-04-12 17:08 UTC, merged