Fix null search service checking
bitwarden/jslib pull request #372
Opened 2021-05-07 20:06 UTC by MGibson1

# Overview

#356 incorrectly assumes that the `searchService` generator in `cipherService` will always be available. CLI does not currently use SearchService so this is null. A null check is added where `searchService` is accessed.

# Files Changed
* **cipher.service**: Check null search service 
* **baseProgram.ts**: chalk has been updated and now exports two objects, set the default export as `chalk` for use in responses.

2021-05-07 20:18 UTC, kspearrin approved these changes

2021-05-07 20:55 UTC, MGibson1 commented
@Hinton it looks like these failures are due to the package updates. Does ubuntu not have the latest chalk version available or something?

2021-05-07 22:29 UTC, Hinton requested changes
@MGibson1 Looks like some old code managed to sneak into `baseProgram`. We no longer need to do `chalk = chk.default`.

2021-05-07 22:29 UTC, Hinton commented on src/cli/baseProgram.ts
> +const chalk = chk.default;
Remove.

2021-05-07 22:29 UTC, Hinton commented on src/cli/baseProgram.ts
> +import * as chk from 'chalk';
Revert

2021-05-10 08:35 UTC, Hinton approved these changes

2021-05-10 14:52 UTC, merged