Remove dollar signs ($) from URLs before parsing
bitwarden/jslib pull request #411
Opened 2021-06-16 04:29 UTC by eliykat

## Objective

`tldjs` does not parse dollar signs in URIs correctly and they're generally illegal characters anyway. See report here: https://app.asana.com/0/1169444489336079/1200474469788269/f.

## Code changes

* strip dollar signs from URI before calling `getDomain()`.

jslib will need to be updated in browser after this is merged.

2021-06-16 08:16 UTC, Hinton commented
What happens if you use another character like `!`? Tldjs has a `isValid` function could potentially be used (return null on invalid). https://github.com/oncletom/tld.js/blob/b758887c0d01a12b6c0f048a544377e8d44368db/lib/is-valid.js#L40

2021-06-16 10:36 UTC, cscharf requested changes

2021-06-16 10:36 UTC, cscharf commented on common/src/misc/utils.ts
> +        uriString = uriString.replace(/\$/g, '').trim();
I agree with Oscar, please remove this line

2021-06-16 10:36 UTC, cscharf commented on common/src/misc/utils.ts
>          }
Down below line 213 after the `data:` check. Add another  check `tldjs.isValid()` and if not valid, then return `null`. Follow the patterns for calling `tldjs` as also seen below.

2021-06-17 01:45 UTC, eliykat commented
I've updated this to use `tldjs.isValid`. Note that the type definitions for `isValid` indicate that it's deprecated in favour of `isValidHostname`. However, `isValidHostname` isn't actually implemented in the installed npm package in `node_modules`. There seems to be [some confusion about this](https://github.com/oncletom/tld.js/issues/133). I think it's a mismatch between the type definitions and the current npm package that we can ignore.

Also, `isValid` only accepts a hostname (not full url), however we already have `Util.getHostname` which doesn't use `tldjs` and which appears to parse symbols correctly, so I thought that was ok to use for this purpose.

2021-06-17 07:58 UTC, Hinton commented on common/src/misc/utils.ts
> +                const validHostname = tldjs?.isValid != null ? tldjs.isValid(url.hostname) : true;
Do we need to update our noop implementation as well? (Always return true perhaps)

2021-06-22 16:49 UTC, cscharf approved these changes

2021-06-22 20:00 UTC, merged