Added creditCardNumber pipe for viewing saved card numbers properly
bitwarden/jslib pull request #590
Opened 2021-12-27 00:23 UTC by AmGarera

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Added the creditCardNumber pipe for viewing saved card numbers properly formatted. Supports all available brands selectable from the existing dropdown. PRs to the other repos will follow and be linked to this PR.
## Code changes

- **credit-card-number.pipe.ts** Added this file because it is a new pipe created to handle credit card formatting when viewing a saved card. referenced issues #427 
## Testing requirements
Test cards should be created for all available brands and their available known formats. I've done this locally so I can submit testing screenshots or whatever is deemed appropriate.

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-01-12 11:35 UTC, Hinton commented
Hi @AmGarera,

Thanks for your contribution. This looks a bit difficult to maintain in the current format.

I think we need to look into creating a dictionary with the different lengths that can be more easily maintained, and reduse code duplication. Something similar to this:

```typescript
const numberFormats = {
  "visa": [
    [16, [4, 4, 4, 4]]
 ],
 "maestro": [
    [16, [4, 4, 4, 4]],
    [13, [4, 4, 5]],
    [14, [4, 6, 5]],
    [16, [4, 4, 4, 4, 3]],
  ],
}
```

If no card type is found, we should default the format to `4, 4, 4, 4`.

Using the lookup table we could then format the string accordingly.

2022-01-29 22:38 UTC, AmGarera commented
@Hinton I've made changes based on your feedback. Please have another look when you have the time. Thanks.

2022-03-14 08:56 UTC, Hinton requested changes
Apologies for the late review.

I believe we can clean up the code a bit further since it's a bit difficult to follow with all the loops. I've added a couple of suggestions which I believe will simplify the logic a fair bit while still retaining it's functionality.

Could you also please run `npm run prettier` which will make it a bit more readable.

Thanks!

2022-03-14 08:56 UTC, Hinton commented on angular/src/pipes/credit-card-number.pipe.ts
> +    numberFormats = {
Since we don't plan on modifying these lets move them outside the class as a `const`.

2022-05-02 12:22 UTC, Hinton commented
![image](https://user-images.githubusercontent.com/137855/166232746-8da0a9fc-c25c-44ed-8acd-03905c403bcc.png)
![image](https://user-images.githubusercontent.com/137855/166232763-d452dccc-78fb-42c5-80e8-f1e132362ac4.png)

2022-05-02 14:36 UTC, djsmith85 approved these changes
Looks good.

@AmGarera Thank you very much for your contribution!

2022-05-02 14:52 UTC, merged